# Generated by Django 5.1.2 on 2024-10-11 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expirations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='expiration_date',
        ),
        migrations.CreateModel(
            name='Expiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
                ('upc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expirations.food')),
            ],
        ),
    ]
